# Generated by Django 5.0.3 on 2024-05-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_pastorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastorder',
            name='user',
        ),
    ]
