# Generated by Django 5.0.3 on 2024-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_pastorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorder',
            name='order_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
